version: "3"
services:
  user-service:
    volumes:
      - ./userService/app:/app
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    build:
      context: ./userService/app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - user-db

  user-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./userDB/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./userDB/mysql_data:/var/lib/mysql
      - ./userDB/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ecc
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: users
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci