POST http://localhost:3000/users/update/2 
Content-Type: application/json

{ "id":2, "name": "更新済み" }

###

POST http://localhost:3000/users
Content-Type: application/json

{"name":"テスト太郎","password":"password","email":"test3@gmail.com","apikey":"AIzaSyDKY9T6Z7XYPRlCx6fLdfeujLfmPnDkldk","last_video":"videoid"}

###

GET http://localhost:3000/users

###
